# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/twister/Dropbox/novelty_assistant/gui/main_form.ui'
#
# Created: Thu Nov 22 00:50:25 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(467, 399)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMain.sizePolicy().hasHeightForWidth())
        frmMain.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/main_64.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        frmMain.setSizeGripEnabled(False)
        self.gridLayout_3 = QtGui.QGridLayout(frmMain)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(frmMain)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabTasks = QtGui.QWidget()
        self.tabTasks.setObjectName(_fromUtf8("tabTasks"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabTasks)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.statusWidget = QtGui.QWidget(self.tabTasks)
        self.statusWidget.setMaximumSize(QtCore.QSize(16777215, 35))
        self.statusWidget.setObjectName(_fromUtf8("statusWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.statusWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.countLabel = tasks_count_label(self.statusWidget)
        self.countLabel.setObjectName(_fromUtf8("countLabel"))
        self.horizontalLayout_2.addWidget(self.countLabel)
        self.statusLabel = tasks_status_label(self.statusWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.horizontalLayout_2.addWidget(self.statusLabel)
        self.gridLayout_2.addWidget(self.statusWidget, 3, 0, 1, 1)
        self.tl = task_list(self.tabTasks)
        self.tl.setObjectName(_fromUtf8("tl"))
        self.gridLayout_2.addWidget(self.tl, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(self.tabTasks)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdNew = QtGui.QPushButton(self.frame)
        self.cmdNew.setAutoDefault(False)
        self.cmdNew.setObjectName(_fromUtf8("cmdNew"))
        self.horizontalLayout.addWidget(self.cmdNew)
        self.cmdSearch = QtGui.QPushButton(self.frame)
        self.cmdSearch.setMaximumSize(QtCore.QSize(24, 16777215))
        self.cmdSearch.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search_16.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdSearch.setIcon(icon1)
        self.cmdSearch.setAutoDefault(False)
        self.cmdSearch.setObjectName(_fromUtf8("cmdSearch"))
        self.horizontalLayout.addWidget(self.cmdSearch)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.dt = QtGui.QDateEdit(self.frame)
        self.dt.setCalendarPopup(True)
        self.dt.setObjectName(_fromUtf8("dt"))
        self.horizontalLayout.addWidget(self.dt)
        self.cmdRefresh = QtGui.QPushButton(self.frame)
        self.cmdRefresh.setAutoDefault(False)
        self.cmdRefresh.setFlat(False)
        self.cmdRefresh.setObjectName(_fromUtf8("cmdRefresh"))
        self.horizontalLayout.addWidget(self.cmdRefresh)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.searchWidget = QtGui.QWidget(self.tabTasks)
        self.searchWidget.setMinimumSize(QtCore.QSize(0, 34))
        self.searchWidget.setMaximumSize(QtCore.QSize(16777215, 34))
        self.searchWidget.setObjectName(_fromUtf8("searchWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.searchWidget)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.searchWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.txtSearchText = QtGui.QLineEdit(self.searchWidget)
        self.txtSearchText.setMinimumSize(QtCore.QSize(220, 0))
        self.txtSearchText.setMaximumSize(QtCore.QSize(220, 16777215))
        self.txtSearchText.setObjectName(_fromUtf8("txtSearchText"))
        self.horizontalLayout_3.addWidget(self.txtSearchText)
        self.cmdCancelSearch = QtGui.QPushButton(self.searchWidget)
        self.cmdCancelSearch.setMaximumSize(QtCore.QSize(24, 16777215))
        self.cmdCancelSearch.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cancel_16.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCancelSearch.setIcon(icon2)
        self.cmdCancelSearch.setAutoDefault(False)
        self.cmdCancelSearch.setObjectName(_fromUtf8("cmdCancelSearch"))
        self.horizontalLayout_3.addWidget(self.cmdCancelSearch)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.searchWidget, 1, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/work_32.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabTasks, icon3, _fromUtf8(""))
        self.tabTime = QtGui.QWidget()
        self.tabTime.setObjectName(_fromUtf8("tabTime"))
        self.gridLayout = QtGui.QGridLayout(self.tabTime)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_3 = QtGui.QWidget(self.tabTime)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblWeek = timesheet_grid(self.widget_3)
        self.tblWeek.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblWeek.setObjectName(_fromUtf8("tblWeek"))
        self.tblWeek.setColumnCount(0)
        self.tblWeek.setRowCount(0)
        self.verticalLayout.addWidget(self.tblWeek)
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.tabTime)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmdComing = QtGui.QPushButton(self.widget_2)
        self.cmdComing.setMinimumSize(QtCore.QSize(69, 0))
        self.cmdComing.setMaximumSize(QtCore.QSize(69, 16777215))
        self.cmdComing.setAutoDefault(False)
        self.cmdComing.setObjectName(_fromUtf8("cmdComing"))
        self.horizontalLayout_4.addWidget(self.cmdComing)
        self.cmdLeaving = QtGui.QPushButton(self.widget_2)
        self.cmdLeaving.setMinimumSize(QtCore.QSize(69, 0))
        self.cmdLeaving.setMaximumSize(QtCore.QSize(69, 16777215))
        self.cmdLeaving.setAutoDefault(False)
        self.cmdLeaving.setObjectName(_fromUtf8("cmdLeaving"))
        self.horizontalLayout_4.addWidget(self.cmdLeaving)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.cmdRefreshTimeSheet = QtGui.QPushButton(self.widget_2)
        self.cmdRefreshTimeSheet.setAutoDefault(False)
        self.cmdRefreshTimeSheet.setObjectName(_fromUtf8("cmdRefreshTimeSheet"))
        self.horizontalLayout_4.addWidget(self.cmdRefreshTimeSheet)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/date_time_32.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabTime, icon4, _fromUtf8(""))
        self.tabServices = QtGui.QWidget()
        self.tabServices.setObjectName(_fromUtf8("tabServices"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabServices)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget = QtGui.QWidget(self.tabServices)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeServices = services_tree(self.widget)
        self.treeServices.setIconSize(QtCore.QSize(24, 24))
        self.treeServices.setObjectName(_fromUtf8("treeServices"))
        self.verticalLayout_2.addWidget(self.treeServices)
        self.verticalLayout_3.addWidget(self.widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/service_32.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabServices, icon5, _fromUtf8(""))
        self.tabDinner = QtGui.QWidget()
        self.tabDinner.setObjectName(_fromUtf8("tabDinner"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabDinner)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_4 = QtGui.QWidget(self.tabDinner)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.cmdAllDinnerOrdersToday = QtGui.QPushButton(self.widget_4)
        self.cmdAllDinnerOrdersToday.setObjectName(_fromUtf8("cmdAllDinnerOrdersToday"))
        self.horizontalLayout_5.addWidget(self.cmdAllDinnerOrdersToday)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.frame_2 = QtGui.QFrame(self.tabDinner)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.lblTodayMenu = QtGui.QLabel(self.frame_2)
        self.lblTodayMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTodayMenu.setOpenExternalLinks(True)
        self.lblTodayMenu.setObjectName(_fromUtf8("lblTodayMenu"))
        self.verticalLayout_5.addWidget(self.lblTodayMenu)
        self.widget_5 = QtGui.QWidget(self.frame_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 2, 2, 1, 1)
        self.chkMenuSalad = QtGui.QCheckBox(self.widget_5)
        self.chkMenuSalad.setObjectName(_fromUtf8("chkMenuSalad"))
        self.gridLayout_4.addWidget(self.chkMenuSalad, 1, 1, 1, 1)
        self.cmdCreateOrder = QtGui.QPushButton(self.widget_5)
        self.cmdCreateOrder.setObjectName(_fromUtf8("cmdCreateOrder"))
        self.gridLayout_4.addWidget(self.cmdCreateOrder, 5, 1, 1, 1)
        self.chkMenuFirst = QtGui.QCheckBox(self.widget_5)
        self.chkMenuFirst.setObjectName(_fromUtf8("chkMenuFirst"))
        self.gridLayout_4.addWidget(self.chkMenuFirst, 2, 1, 1, 1)
        self.chkMenuSecond = QtGui.QCheckBox(self.widget_5)
        self.chkMenuSecond.setObjectName(_fromUtf8("chkMenuSecond"))
        self.gridLayout_4.addWidget(self.chkMenuSecond, 3, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 6, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 4, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_5)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.frame_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dinner_32.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabDinner, icon6, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(frmMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QtGui.QApplication.translate("frmMain", "Novelty Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.countLabel.setText(QtGui.QApplication.translate("frmMain", "Количество задач", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("frmMain", "Общее время", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdNew.setToolTip(QtGui.QApplication.translate("frmMain", "CTRL+N", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdNew.setText(QtGui.QApplication.translate("frmMain", "Новая", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdNew.setShortcut(QtGui.QApplication.translate("frmMain", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSearch.setToolTip(QtGui.QApplication.translate("frmMain", "Поиск (CTRL+F)", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSearch.setShortcut(QtGui.QApplication.translate("frmMain", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmMain", "Отобразить на дату:", None, QtGui.QApplication.UnicodeUTF8))
        self.dt.setDisplayFormat(QtGui.QApplication.translate("frmMain", "dd.MM.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRefresh.setToolTip(QtGui.QApplication.translate("frmMain", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRefresh.setText(QtGui.QApplication.translate("frmMain", "Обновить", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRefresh.setShortcut(QtGui.QApplication.translate("frmMain", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmMain", "Поиск:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancelSearch.setToolTip(QtGui.QApplication.translate("frmMain", "Отмена (ESC)", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancelSearch.setShortcut(QtGui.QApplication.translate("frmMain", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabTasks), QtGui.QApplication.translate("frmMain", "Выполненные работы", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdComing.setText(QtGui.QApplication.translate("frmMain", "Приход", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLeaving.setText(QtGui.QApplication.translate("frmMain", "Уход", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRefreshTimeSheet.setToolTip(QtGui.QApplication.translate("frmMain", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRefreshTimeSheet.setText(QtGui.QApplication.translate("frmMain", "Обновить", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdRefreshTimeSheet.setShortcut(QtGui.QApplication.translate("frmMain", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabTime), QtGui.QApplication.translate("frmMain", "Приход / уход", None, QtGui.QApplication.UnicodeUTF8))
        self.treeServices.headerItem().setText(0, QtGui.QApplication.translate("frmMain", "Список серверов приложений", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabServices), QtGui.QApplication.translate("frmMain", "Серверы приложений", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAllDinnerOrdersToday.setText(QtGui.QApplication.translate("frmMain", "Все заказы на сегодня", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmMain", "Меню на сегодня:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTodayMenu.setText(QtGui.QApplication.translate("frmMain", "Идёт обновление, подождите...", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMenuSalad.setText(QtGui.QApplication.translate("frmMain", "Салат", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCreateOrder.setText(QtGui.QApplication.translate("frmMain", "Заказать", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMenuFirst.setText(QtGui.QApplication.translate("frmMain", "Первое", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMenuSecond.setText(QtGui.QApplication.translate("frmMain", "Второе", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabDinner), QtGui.QApplication.translate("frmMain", "Заказ обедов", None, QtGui.QApplication.UnicodeUTF8))

from timesheet_grid import timesheet_grid
from services_tree import services_tree
from task_list import tasks_count_label, tasks_status_label, task_list
import novelty_assistant_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmMain = QtGui.QDialog()
    ui = Ui_frmMain()
    ui.setupUi(frmMain)
    frmMain.show()
    sys.exit(app.exec_())

